apiVersion: apps/v1
kind: Deployment
metadata:
  name: classification-api
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: classification-api
  template:
    metadata:
      labels:
        app: classification-api
    spec:
      containers:
      - name: classification-api
        image: classification-api:latest  
        imagePullPolicy: Never          
        ports:
        - containerPort: 8000          
---
apiVersion: v1
kind: Service
metadata:
  name: classification-api-service
spec:
  selector:
    app: classification-api
  ports:
  - protocol: TCP
    port: 80        # Expose on port 80
    targetPort: 8000  # Map to port 8000 of the container
  type: NodePort    
